matrix:
  include:
    - language: ruby
      rvm:
        - 2.5.0
      services:
        - docker
      script:
        - docker run --rm -v ${PWD}:/data mivok/markdownlint ./*.md _posts
    - language: ruby
      rvm:
        - 2.5.0
      before_script:
        - chmod +x ./script/htmlproofer # or do this locally and commit
      # Assume bundler is being used, therefore
      # the `install` step will run `bundle install` by default.
      script: ./script/htmlproofer
      # branch whitelist, only for GitHub Pages
      branches:
        only:
          - gh-pages
          - /.*/
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      sudo: false

