---
title: Erik Dolinsky
email: erik@dolins.ky
username: Erik Dolinsky
job_title: Software Engineer
description: >-
  Erik Dolinsky's landing page. Software Engineering and DevOps blog.
baseurl: ""
url: ""
fqdn: www.dolins.ky
twitter_username: erikdolinsky
github_username: edolinsky
linkedin_public_url: erikdolinsky
profile_picture: /assets/img/profile_picture.jpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

links:
  section_1:
    - title: home
      url: /
      key_trigger: h
    - title: posts
      url: /posts
      key_trigger: p
    - title: tags
      url: /tags
      key_trigger: t
    - title: about me
      url: /about
      key_trigger: a
  section_2:
    - title: open menu
      key_trigger: space
    - title: close menu
      key_trigger: esc
    - title: search
      key_trigger: s
